# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181220_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='mv',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
